### PR TITLE
retrieve chat history with specifically matched individuals

### PR DESCRIPTION
**Pull request by fahmedk**

### CODE REVIEW

**Comment by Hassan5123** [comment]
This function is great. However, more descriptive error messages would be helpful. Additionally, a check to ensure "userId" exists before querying the database would make the implementation cleaner.

**Comment by melidobello** [comment]
This is a solid implementation! You might also include sorting the messages by createdAt before returning them to ensure they are always displayed in the correct chronological order.

**Comment by Fahim8230** [comment]
This is a solid implementation! Adding more descriptive error messages and validating that "userId" exists before querying the database would improve reliability. Also, consider sorting messages by `createdAt` to ensure they are always displayed in the correct chronological order.

**Comment by jhenrynyc** [comment]
This update integrates chat history retrieval through the `getChatHistory` function, which is well-structured and includes validation for the authenticated and matched user IDs. The use of MongoDB's `$all` operator in the query ensures both participants are correctly matched in the chat, and the addition of `.populate` enhances the returned data by including sender details for messages. The error handling is robust, providing clear feedback for missing or invalid matched user IDs, as well as handling cases where no chat history is found. The route addition for `getChatHistory` is logically placed and adheres to the project's existing conventions. Overall, this is a solid addition to enhance the chat functionality, though adding corresponding tests would further validate its reliability and edge case handling.

**Pull request merged**
